apiVersion: v1
kind: ConfigMap
metadata:
  name: es-curator-config
data:
  # Connection and logging settings for Elasticsearch
  config.yml: |
    client:
      hosts: ["efk-stack-elasticsearch.default.svc.cluster.local"]
      port: 9200
      timeout: 30
    logging:
      loglevel: INFO

  # Curator actions: delete any logstash-* index older than 7 days
  actions.yml: |
    actions:
      1:
        action: delete_indices
        description: >-
          Delete logstash indices older than 7 days
        options:
          ignore_empty_list: True
        filters:
          - filtertype: pattern
            kind: prefix
            value: logstash-
          - filtertype: age
            source: name
            direction: older
            unit: minutes
            unit_count: 4
            timestring: '%Y.%m.%d'

